version: '3.0'

services:

  redis:
    image: redis
  
  rabbitmq:
    image: 'rabbitmq:management'

  SystemService:
      image: 'SystemService:${TAG:-latest}'
      build:
        context: ../../
        dockerfile: BasicServices/SystemService/SystemService.Api/Dockerfile
      depends_on:
        - redis

 