version: '3.0'

services:

  redis:
    image: redis
  
  rabbitmq:
    image: 'rabbitmq:management'

  HostWeb:
      image: 'HostWeb:${TAG:-latest}'
      build:
        context: ../../
        dockerfile: Framework/HostWeb/Dockerfile

  AuthWeb:
      image: 'AuthWeb:${TAG:-latest}'
      build:
        context: ../../
        dockerfile: Framework/AuthWeb/Dockerfile

  ApiGateway:
      image: 'ApiGateway:${TAG:-latest}'
      build:
        context: ../../
        dockerfile: Framework/ApiGateway/Dockerfile
      depends_on:
        - AuthWeb

  SystemService:
      image: 'SystemService:${TAG:-latest}'
      build:
        context: ../../
        dockerfile: BasicServices/SystemService/SystemService.Api/Dockerfile
      depends_on:
        - redis

 