apiVersion: apps/v1
kind: Deployment
metadata:
  name: systemservice-api
spec:
  selector:
    matchLabels:
      app: systemservice-api
  replicas: 1
  template:
    metadata:
      labels:
        app: systemservice-api
    spec:
      containers:
        - name: systemservice-api
          image: "systemservice-api"
          imagePullPolicy: IfNotPresent
          env:
          - name: ASPNETCORE_ENVIRONMENT
            value: Development.Kube
          ports:
            - name: http
              containerPort: 80
          readinessProbe:
            httpGet:
              path: /api/heathcheck/readiness
              port: 80
              scheme: HTTP 
            initialDelaySeconds: 30
            periodSeconds: 60 
          livenessProbe:
            httpGet:
              path: /api/heathcheck/liveness
              port: 80
              scheme: HTTP 
            initialDelaySeconds: 120
            periodSeconds: 60

---

kind: Service
apiVersion: v1
metadata:
  name: systemservice-api
spec:
  selector:
    app: systemservice-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: http
